---
# Install MariaDB on Debian Based systems

- name: Debian | Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags:
    - install
    - repository

- name: Debian | Install support package gnupg
  apt:
    state: present
    name: gnupg
  tags:
    - install
    - repository

- name: Debian | Adding MariaDB GPG key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present
  tags:
    - install
    - repository

- name: Debian | Create MariaDB {{ mariadb_version }} repository
  apt_repository:
    repo: "deb [arch=amd64] http://mariadb.mirror.globo.tech/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present
    filename: "MariaDB-{{ mariadb_version }}"
    update_cache: yes
  tags:
    - install
    - repository

- name: Debian | Install MariaDB {{ mariadb_version }} packages
  apt:
    name:
      - mariadb-server
    update_cache: yes
    cache_valid_time: 3600
    state: present
  tags:
    - install
    - packages
