---
# tasks file for ansible-role-mariadb

- name: Include distribution variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always
    - install
    - configure

- name: Install RHEL
  include: install.rhel.yml
  when: ansible_os_family == "RedHat"
  tags:
    - install
    - configure

- name: Install Debian
  include: install.debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - install
    - configure

- name: Configure
  include: configure.yml
  tags:
    - directories
    - configure

- name: Flush all the handlers
  meta: flush_handlers

- name: Security Configs
  include: security.config.yml
  tags:
    - security-configs
    - configure
