---
- name: Converge
  hosts: 
    - ubuntu2004
    #- debian10
    - centos8  
  tasks:
    - name: Install rsync
      package:
        name: rsync
        state: latest

    - name: "Include ansible-role-mariadb"
      include_role:
        name: "ansible-role-mariadb"
