---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: 
    - debian10
    - centos8  
    - ubuntu2004
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
