---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: 
    #- ubuntu2004
    - debian10
    #- centos8
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
